# Numpy

- Numerical python
- Python library used for working with arrays
- Created in 2005 by Travis Oliphant
- Lists that serves the purpose of arrays but slow to process
- Numpy aims to provide an array object that is upto 50x faster than traditional python lists

In [1]:
import numpy as np
import sys
s=range(1000)
print("size of each element of list in bytes: ",sys.getsizeof(s))
print("size of whole list in bytes: ",sys.getsizeof(s)*len(s))

size of each element of list in bytes:  48
size of whole list in bytes:  48000


In [2]:
D=np.arange(1000)
print("size of each element of numpy array in bytes: ",D.itemsize)
print("size of whole numpy array in bytes: ",D.itemsize*D.size)

size of each element of numpy array in bytes:  4
size of whole numpy array in bytes:  4000


### ndim

In [3]:
import numpy as np 
arr=np.array(42)
print(arr)
print(arr.ndim)
print(type(arr))

42
0
<class 'numpy.ndarray'>


In [6]:
import numpy as np 
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
print(type(arr))

[[1 2 3 4]
 [5 6 7 8]]
2
<class 'numpy.ndarray'>


In [8]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [9]:
arr=np.array([[[1,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[list([1, 3]) list([4, 5, 6])]
 [list([7, 8, 9]) list([10, 11, 12])]]
2


<ipython-input-9-427daafc6fb5>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=np.array([[[1,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [10]:
arr=np.array([[[1,2,3,4,5]]])
print(arr)
print(arr.ndim) # dimension

[[[1 2 3 4 5]]]
3


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3])
print(arr[2]*arr[4])

4
15


In [12]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])
print(arr[1,1])
print(arr[0,3])
print(arr[1,2])

2
6
4
7


In [14]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,1,1])
print(arr[0,0,1])
print(arr[1,0,2])
print(arr[2,2,0])

6
11
2
9


IndexError: index 2 is out of bounds for axis 0 with size 2

In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])
print(arr[1,0:3])
print(arr[0,-3])

print(arr[0:2,2])
print(arr[0:2,0:3]) # no. of slicing increases no. of dimensions

print(type(arr[0:2,2]))
print(type(arr[0,-1]))

print((arr[0:2,0:3]).ndim)
print((arr[0:2,2]).ndim)

8
[5 6 7]
2
[3 7]
[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
<class 'numpy.int32'>
2
1


In [27]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,0:2,0:2])
print(arr[0:2,0:2,0:2].ndim)

3
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [32]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,0:2,2])
print(arr[0:2,0:2,2].ndim)

[[ 3  6]
 [ 9 12]]
2


In [30]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,1,2])
print(arr[0:2,1,2].ndim)

[ 6 12]
1


### shape

In [33]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1.ndim)
print(arr1.shape)

print(arr2.ndim)
print(arr2.shape)

print(arr3.ndim)
print(arr3.shape)

1
(5,)
2
(2, 4)
3
(2, 2, 3)


### ndmin

In [36]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


### reshape

In [37]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(3,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [39]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(1,6)
print(newarr)

[[1 2 3 4 5 6]]


In [40]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(6,1)
print(newarr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [41]:
import numpy as np 
arr1=np.array([1,2,3,4,5])
newarr=arr1.reshape(2,3)
print(newarr)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [42]:
import numpy as np 
arr1=np.array([1,2,3,4,5])
newarr=arr1.reshape(2,-1)
print(newarr)

ValueError: cannot reshape array of size 5 into shape (2,newaxis)

In [43]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


### base

In [44]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,-1).base
print(newarr)

[1 2 3 4 5 6]


## iteration

In [45]:
arr = np.array([[[1,2,3,4,5]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5


### nditer

In [46]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5


In [48]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
3


## built in functions

### 1. concatenate

In [49]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [50]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [51]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3),axis=1)
print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [62]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [61]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [60]:
import numpy as np
arr1=np.array([[[1,2],[3,4],[1,1]]])
arr2=np.array([[[5,6],[7,8],[2,2]]])
arr=np.concatenate((arr1,arr2),axis=2)
print(arr)
print(arr.shape)

[[[1 2 5 6]
  [3 4 7 8]
  [1 1 2 2]]]
(1, 3, 4)


### 2. split

In [63]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [64]:
import numpy as np
arr=np.array([1,2,3,4])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2]), array([3, 4])]


In [66]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr,4)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [67]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


### 3. where

In [68]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4)
print(x)

(array([3, 6], dtype=int64),)


In [69]:
import numpy as np
arr=np.array([[1,2],[3,4],[4,5]])
x=np.where(arr==4)
print(x)

(array([1, 2], dtype=int64), array([1, 0], dtype=int64))
